# Dependencies
markdown:         kramdown
highlighter:      rouge


# Setup
title:            'Quantum resources workshop - Jeju 2025'
tagline:          'Quantum resources 2025'
description:      'Workshop on quantum resource theories, taking place between 17 - 21 March 2025 in Jeju, Korea'
url:              "https://2025.quantumresources.science"
baseurl:          ''


author:
  name:           'Hyukjoon Kwon'

paginate:         5

# Custom vars
version:          1.0.0

